elastic-query-service:
  version: v1
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    query-type: 'KAFKA_STATE_STORE'
  query-from-kafka-state-store:
    method: GET
    uri: "http://localhost:8187/kafka-streams-service/get-word-count-by-word/{word}"
    accept: ${elastic-query-service.webclient.accept-type}
  

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: user
  password: ENC(0KybwyexsK+R7+kl+AE5m7ngz/b6NMtECzlJRZPFo1i6B/b9UZ5yvKYvIkOJAKhq)
  roles: USER

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/auth/realms/microservices_realm
          jwk-set-uri: http://localhost:9091/auth/realms/microservices_realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-service'
            client-secret: '12a09c98-c9ec-426f-a588-e8062196f203'
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/microservices_realm
          
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect     

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs
